Add checkTMUXInstalled and checkFileExist functions
installed bash shellcheck and fixed shown errors

diff --git a/minotaur b/minotaur
--- a/minotaur
+++ b/minotaur
@@ -19,9 +19,25 @@ prod_config='conf-prod.json'
 
 current_config="nil"
 
-echo 
-echo "Welcome To Minotaur"
-echo 
+checkTMUXInstalled () {
+    if ! command -v tmux &> /dev/null; then
+        echo
+        echo "Error:"
+        echo "tmux is not installed."
+        echo "Install tmux and rerun the program."
+        echo
+        echo
+        exit 1
+    fi
+}
+
+Begin () {
+    echo 
+    echo "Welcome To Minotaur"
+    echo 
+
+    checkTMUXInstalled
+}
 
 getConfigProp () {
     config="$(cat "${0%/*}"/"$current_config" | jq -r ".$1")"
@@ -69,6 +85,17 @@ host_check() {
     fi
 }
 
+checkfileExist () {
+    file=$1
+    if [ ! -f "$file" ]; then 
+            echo
+            echo "The file you want to copy does not exist."
+            echo "Path: $file"
+            echo 
+            exit 1
+    fi
+}
+
 scp_Command() {
     # $1 key, $2 file, $3 username, $4 ip
     local key="$1"
@@ -77,7 +104,7 @@ scp_Command() {
     local ip="$4"
     local isTag=false
 
-    if [ ! -z $5 ]; then
+    if [ ! -z "$5" ]; then
         echo "setting is tag to true"
         local isTag=true
     fi
@@ -86,7 +113,7 @@ scp_Command() {
         echo "Couldnt get IP from config file."
     fi
 
-    hostIsUp="$(host_check $ip)"
+    hostIsUp="$(host_check "$ip")"
     echo "Ping Host: $ip"
     echo "Ping Response: $hostIsUp"
 
@@ -98,13 +125,13 @@ scp_Command() {
     fi 
     echo "Copying to IP: $ip"
     echo "Ping host up: $hostIsUp"
-    echo Running: scp -o ConnectTimeout=5 -i $key -r "$file_to_copy" "$username"@"$ip":~
+    echo Running: scp -o ConnectTimeout=5 -i "$sshKey" -r "$file_to_copy" "$username"@"$ip":~
 
     if [ $isTag = true ]; then
-        tmux send-keys -t $SESSION_NAME "scp -o ConnectTimeout=5 -i $key -r "$file_to_copy" "$username"@"$ip":~" Enter
+        tmux send-keys -t $SESSION_NAME "scp -o ConnectTimeout=5 -i $sshKey -r $file_to_copy $username@$ip:~" Enter
         tmux new-window -t $SESSION_NAME
     else
-        scp -o ConnectTimeout=5 -i $key -r "$file_to_copy" "$username"@"$ip":~
+        scp -o ConnectTimeout=5 -i "$sshKey" -r "$file_to_copy" "$username"@"$ip":~
     fi
 
 }
@@ -121,8 +148,13 @@ while getopts 'cszt:f:b:i:e:hp' flag; do
     e) environment_flag="${OPTARG}" ;;
     f) files="${OPTARG}" ;;
     h) print_usage ;;
+    *) print_usage ;;
   esac
 done
+
+# Script Into
+
+Begin
 
 echo
 echo "Defaults: "
@@ -143,6 +175,7 @@ elif [[ $environment_flag = "pre" ]]; then
 elif [[ $environment_flag = "prod" ]]; then 
     current_config=$prod_config
 else
+    echo "No environment selected"
     echo "Setting Current environment to default of pre prod"
     echo "Config file: $pre_config"
     echo
@@ -150,10 +183,10 @@ else
 fi
 
 # Get ssh key from config file
-key="$(getConfigProp "sshKey")"
+sshKey="$(getConfigProp "sshKey")"
 
-# password unimplemented
-password="$(getConfigProp "password")"
+# TODO ... password unimplemented
+# password="$(getConfigProp "password")"
 
 # if no key and no password then exit
 # if both the prefer key
@@ -166,7 +199,7 @@ fi
 
 if [ $copy_flag = false ] && [ $ssh_flag = false ] ; then
     if [ $tmux_help = true ]; then 
-        cat ${0%/*}/TMUX_HELP.txt
+        cat "${0%/*}"/TMUX_HELP.txt
         exit 0
     fi
     echo "No copy -c or SSH -s flags set"
@@ -197,13 +230,7 @@ if [ $copy_flag = true ] ; then
         exit 1
     fi
 
-    if [ ! -f $files ]; then 
-        echo
-        echo "The file you want to copy does not exist."
-        echo "Path: $files"
-        echo 
-        exit 1
-    fi
+    checkfileExist "$files"
 
     if [ "$tag_flag" != "nil" ] ; then 
         # has flag tag for copy
@@ -220,7 +247,7 @@ if [ $copy_flag = true ] ; then
             else 
                 if [[ $b == *"," ]]; then
                     # remove comma
-                    b=${b::-1}
+                    b=${b%?}
                 fi
 
                 boxName=$b
@@ -236,7 +263,7 @@ if [ $copy_flag = true ] ; then
                     
                     if [ "$specificUsername" != "null" ]; then
                         echo "$boxName has its own username defined"
-                        echo "Logging into box using username: $specificUsername $(echo $specificUsername != null) "
+                        echo "Logging into box using username: $specificUsername"
                         username="$specificUsername"
                     fi
 
@@ -244,7 +271,7 @@ if [ $copy_flag = true ] ; then
                     echo "Sending to $b"
 
                     tmux rename-window "${b:1:-1}"
-                    scp_Command $key $files $username $ip true
+                    scp_Command "$sshKey" "$files" "$username" "$ip" true
                     tmux attach -t $SESSION_NAME
                 fi
             fi
@@ -264,7 +291,7 @@ if [ $copy_flag = true ] ; then
             else 
                 if [[ $b == *"," ]]; then
                     # echo "has comma"
-                    b=${b::-1}
+                    b=${b%?}
                 fi
 
                 boxName=$b
@@ -285,7 +312,7 @@ if [ $copy_flag = true ] ; then
 
                     echo "Found single box"
                     echo "Sending to $b"
-                    scp_Command $key $files $username $ip
+                    scp_Command "$sshKey" "$files" "$username" "$ip"
 
                 elif [[ "$ip_flag" != "nil" ]] && [[ "$ip_flag" = "$ip" ]]; then
                     if [ "$specificUsername" != "null" ]; then
@@ -296,7 +323,7 @@ if [ $copy_flag = true ] ; then
 
                     echo "Found single box via ip"
                     echo "Sending to $b"
-                    scp_Command $key $files $username $ip
+                    scp_Command "$sshKey" "$files" "$username" "$ip"
 
                 fi 
             fi
@@ -325,7 +352,9 @@ if [ $ssh_flag = true ] ; then
             else 
                 if [[ $b == *"," ]]; then
                     # echo "has comma"
-                    b=${b::-1}
+                    echo "$b"
+                    b=${b%?}
+                    # b=${b%?}
                 fi
                 # echo "Tag here: $b"
                 boxName=$b
@@ -347,7 +376,7 @@ if [ $ssh_flag = true ] ; then
                         username="$specificUsername"
                     fi
 
-                    hostIsUp="$(host_check $ip)"
+                    hostIsUp="$(host_check "$ip")"
                     echo "Ping Host: $ip"
                     echo "Ping Response: $hostIsUp"
 
@@ -359,9 +388,10 @@ if [ $ssh_flag = true ] ; then
                     fi 
 
                     # echo usename is $username key is ssh_key box is $ip
-                    echo Running: ssh -i $key "$username"@"$ip"
-                    tmux rename-window "${b:1:-1}"
-                    tmux send-keys -t $SESSION_NAME "ssh -o ConnectTimeout=5 -i $key $username@$ip" Enter
+                    echo Running: ssh -i "$sshKey" "$username"@"$ip"
+                    tmux rename-window "${b: -1}"
+                    # tmux rename-window "${b:1:-1}"
+                    tmux send-keys -t $SESSION_NAME "ssh -o ConnectTimeout=5 -i $sshKey $username@$ip" Enter
                     tmux new-window -t $SESSION_NAME
                 fi
             fi
@@ -381,6 +411,7 @@ if [ $ssh_flag = true ] ; then
 
         username="$(getConfigProp "username")"
         box="$(getConfigProp "boxes | keys")"
+        echo "Checking for specific box"
 
         for b in $box
         do
@@ -389,7 +420,8 @@ if [ $ssh_flag = true ] ; then
             else 
                 if [[ $b == *"," ]]; then
                     # echo "has comma"
-                    b=${b::-1}
+                    b=${b%?}
+
                 fi
                 # echo "Tag here: $b"
                 boxName=$b
@@ -397,7 +429,10 @@ if [ $ssh_flag = true ] ; then
                 ip="$(getConfigProp "boxes.$b.ip")"
                 specificUsername="$(getConfigProp "boxes.$b.username")"
 
+                echo "checking $b"
+
                 if [ -z "$boxName" ]; then 
+                echo "No box name"
                     continue
                 fi
 
@@ -410,7 +445,7 @@ if [ $ssh_flag = true ] ; then
                         username="$specificUsername"
                     fi
 
-                    hostIsUp="$(host_check $ip)"
+                    hostIsUp="$(host_check "$ip")"
                     echo "Ping Host: $ip"
                     echo "Ping Response: $hostIsUp"
 
@@ -422,11 +457,11 @@ if [ $ssh_flag = true ] ; then
                         return
                     fi 
 
-                    # echo usename is $username key is $key box is $ip
-                    echo Running: ssh -i $key "$username"@"$ip"
+                    # echo usename is $username key is $sshKey box is $ip
+                    echo Running: ssh -i "$sshKey" "$username"@"$ip"
                     # add code to open in tmux
-                    tmux rename-window ${b:1:-1}
-                    tmux send-keys -t $SESSION_NAME "ssh -o ConnectTimeout=5 -i $key $username@$ip" Enter
+                    tmux rename-window "${b%?}"
+                    tmux send-keys -t $SESSION_NAME "ssh -o ConnectTimeout=5 -i $sshKey $username@$ip" Enter
                     tmux new-window -t $SESSION_NAME
                     
 
@@ -440,7 +475,7 @@ if [ $ssh_flag = true ] ; then
                         username="$specificUsername"
                     fi
 
-                    hostIsUp="$(host_check $ip)"
+                    hostIsUp="$(host_check "$ip")"
                     echo "Ping Host: $ip"
                     echo "Ping Response: $hostIsUp"
 
@@ -451,11 +486,11 @@ if [ $ssh_flag = true ] ; then
                         echo
                         return
                     fi 
-                    # echo usename is $username key is $key box is $ip
-                    echo Running: ssh -i $key "$username"@"$ip"
+                    # echo usename is $username key is $sshKey box is $ip
+                    echo Running: ssh -i "$sshKey" "$username"@"$ip"
                     # add code to open in tmux
-                    tmux rename-window ${b:1:-1}
-                    tmux send-keys -t $SESSION_NAME "ssh -o ConnectTimeout=5 -i $key $username@$ip" Enter
+                    tmux rename-window "${b:1:-1}"
+                    tmux send-keys -t $SESSION_NAME "ssh -o ConnectTimeout=5 -i $sshKey $username@$ip" Enter
                     tmux new-window -t $SESSION_NAME
                     
                 fi 
